# Generated by Django 5.2.5 on 2025-08-13 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Feriado ou Recesso',
                'verbose_name_plural': 'Feriados e Recessos',
            },
        ),
        migrations.CreateModel(
            name='ParametrosSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_upm', models.DecimalField(decimal_places=2, help_text='Valor atual, em Reais, da Unidade Padrão Municipal.', max_digits=10, verbose_name='Valor da UPM (R$)')),
                ('preco_medio_gasolina', models.DecimalField(decimal_places=2, help_text='Preço médio do litro da gasolina para cálculo de deslocamento.', max_digits=10, verbose_name='Preço Médio da Gasolina (R$)')),
            ],
            options={
                'verbose_name': 'Parâmetro do Sistema',
                'verbose_name_plural': 'Parâmetros do Sistema',
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ANALISE_ADMIN', 'Aguardando Análise Administrativa'), ('AG_ASS_SOL', 'Aguardando Assinaturas (Solicitação)'), ('AG_INSCRICAO', 'Aguardando Comprovante de Inscrição'), ('AG_EMPENHO', 'Aguardando Empenho'), ('AG_PAGAMENTO', 'Aguardando Pagamento'), ('AG_PC', 'Aguardando Prestação de Contas'), ('PC_ANALISE', 'PC em Análise (Controle Interno)'), ('AG_ASS_PC', 'Aguardando Assinaturas (PC)'), ('PC_ANALISE_CONT', 'PC em Análise (Contabilidade)'), ('ARQUIVADO', 'Processo Arquivado'), ('CORRECAO', 'Correção Pendente'), ('INDEFERIDO', 'Indeferido'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20)),
                ('objetivo_viagem', models.TextField(verbose_name='Objetivo da Viagem')),
                ('destino', models.CharField(max_length=255, verbose_name='Cidade de Destino')),
                ('data_saida', models.DateTimeField(verbose_name='Data e Hora da Saída')),
                ('data_retorno', models.DateTimeField(verbose_name='Data e Hora do Retorno')),
                ('meio_transporte', models.CharField(choices=[('VEICULO_PROPRIO', 'Veículo Próprio'), ('VEICULO_OFICIAL', 'Veículo Oficial'), ('AEREO', 'Transporte Aéreo'), ('ONIBUS', 'Transporte Rodoviário (Ônibus)'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Meio de Transporte')),
                ('placa_veiculo', models.CharField(blank=True, help_text="Preencher somente se o meio de transporte for 'Veículo Próprio'.", max_length=10, null=True, verbose_name='Placa do Veículo')),
                ('envolve_passagens_aereas', models.BooleanField(default=False, help_text='Marcar esta opção altera o prazo de solicitação para 10 dias úteis.', verbose_name='Viagem envolve compra de passagens aéreas?')),
                ('solicita_pagamento_inscricao', models.BooleanField(default=False, verbose_name='Solicita pagamento de taxa de inscrição?')),
                ('distancia_total_km', models.PositiveIntegerField(blank=True, help_text='Distância de ida e volta calculada automaticamente.', null=True, verbose_name='Distância Total (km)')),
                ('valor_total_diarias', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Total das Diárias (R$)')),
                ('valor_deslocamento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor da Indenização de Deslocamento (R$)')),
                ('valor_taxa_inscricao', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor da Taxa de Inscrição (R$)')),
                ('valor_total_empenhar', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Total a Empenhar (R$)')),
                ('gdrive_folder_id', models.CharField(blank=True, editable=False, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Processo de Diária',
                'verbose_name_plural': 'Processos de Diárias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('gdrive_file_id', models.CharField(max_length=100, unique=True, verbose_name='ID do Arquivo no Drive')),
                ('tipo_documento', models.CharField(choices=[('SOLICITACAO_INICIAL', 'Solicitação Inicial'), ('SOLICITACAO_ASSINADA', 'Solicitação Assinada'), ('COMPROVANTE_INSCRICAO', 'Comprovante de Inscrição'), ('EMPENHO', 'Nota de Empenho'), ('COMPROVANTE_PAGAMENTO', 'Comprovante de Pagamento'), ('RELATORIO_VIAGEM', 'Relatório de Viagem'), ('COMPROVANTE_HOSPEDAGEM', 'Comprovante de Hospedagem'), ('OUTRO', 'Outro')], max_length=30, verbose_name='Tipo do Documento')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.processo')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='ProcessoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, choices=[('RASCUNHO', 'Rascunho'), ('ANALISE_ADMIN', 'Aguardando Análise Administrativa'), ('AG_ASS_SOL', 'Aguardando Assinaturas (Solicitação)'), ('AG_INSCRICAO', 'Aguardando Comprovante de Inscrição'), ('AG_EMPENHO', 'Aguardando Empenho'), ('AG_PAGAMENTO', 'Aguardando Pagamento'), ('AG_PC', 'Aguardando Prestação de Contas'), ('PC_ANALISE', 'PC em Análise (Controle Interno)'), ('AG_ASS_PC', 'Aguardando Assinaturas (PC)'), ('PC_ANALISE_CONT', 'PC em Análise (Contabilidade)'), ('ARQUIVADO', 'Processo Arquivado'), ('CORRECAO', 'Correção Pendente'), ('INDEFERIDO', 'Indeferido'), ('CANCELADO', 'Cancelado')], max_length=20, null=True)),
                ('status_novo', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ANALISE_ADMIN', 'Aguardando Análise Administrativa'), ('AG_ASS_SOL', 'Aguardando Assinaturas (Solicitação)'), ('AG_INSCRICAO', 'Aguardando Comprovante de Inscrição'), ('AG_EMPENHO', 'Aguardando Empenho'), ('AG_PAGAMENTO', 'Aguardando Pagamento'), ('AG_PC', 'Aguardando Prestação de Contas'), ('PC_ANALISE', 'PC em Análise (Controle Interno)'), ('AG_ASS_PC', 'Aguardando Assinaturas (PC)'), ('PC_ANALISE_CONT', 'PC em Análise (Contabilidade)'), ('ARQUIVADO', 'Processo Arquivado'), ('CORRECAO', 'Correção Pendente'), ('INDEFERIDO', 'Indeferido'), ('CANCELADO', 'Cancelado')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('anotacao', models.TextField(blank=True, verbose_name='Anotação / Justificativa')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='core.processo')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Ação')),
            ],
            options={
                'verbose_name': 'Histórico do Processo',
                'verbose_name_plural': 'Históricos dos Processos',
                'ordering': ['-timestamp'],
            },
        ),
    ]
