# Generated by Django 5.2.5 on 2025-08-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_role_alter_profile_cpf_profile_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lotacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lotação'),
        ),
    ]
