# Generated by Django 5.2.5 on 2025-08-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_lotacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='ano',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Ano de criação da solicitação.', null=True, verbose_name='Ano'),
        ),
        migrations.AddField(
            model_name='processo',
            name='gdrive_file_id',
            field=models.CharField(blank=True, editable=False, help_text='ID do Google Doc da solicitação gerada.', max_length=100, verbose_name='ID do Documento no Drive'),
        ),
        migrations.AddField(
            model_name='processo',
            name='numero_diaria',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Número sequencial da diária dentro do ano.', null=True, verbose_name='Número da Diária'),
        ),
        migrations.AlterUniqueTogether(
            name='processo',
            unique_together={('numero_diaria', 'ano')},
        ),
    ]
