# Generated by Django 5.2.5 on 2025-08-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_processo_ano_processo_gdrive_file_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='processo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='processo',
            name='numero',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Número sequencial do processo dentro do ano (gerado automaticamente).', null=True, verbose_name='Número Sequencial'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='ano',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Ano em que a diária foi gerada (preenchido automaticamente).', null=True, verbose_name='Ano do Processo'),
        ),
        migrations.RemoveField(
            model_name='processo',
            name='gdrive_file_id',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='numero_diaria',
        ),
    ]
