# Generated by Django 5.2.5 on 2025-08-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_processo_unique_together_processo_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='justificativa_viagem_antecipada',
            field=models.TextField(blank=True, help_text="Justificativa quando o solicitante marca 'Solicita viagem antecipada'.", null=True, verbose_name='Justificativa de Viagem Antecipada'),
        ),
        migrations.AddField(
            model_name='processo',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações adicionais fornecidas pelo solicitante.', null=True, verbose_name='Observações'),
        ),
    ]
