# Generated by Django 5.2.5 on 2025-08-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_processo_justificativa_viagem_antecipada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='observacoes',
        ),
        migrations.AlterField(
            model_name='processo',
            name='justificativa_viagem_antecipada',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa da Viagem Antecipada'),
        ),
    ]
