# Generated by Django 5.2.5 on 2025-08-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_processo_observacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
