# Generated by Django 5.2.5 on 2025-08-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_processo_observacoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="gdrive_file_url",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="URL do Arquivo no Drive",
            ),
        ),
    ]
