# Generated by Django 5.2.5 on 2025-08-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_documento_gdrive_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
