# Generated by Django 5.2.5 on 2025-08-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_profile_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
